### ISSUE TITLE
higlass-python.log being created everywhere.

### ISSUE THREAD

**Issue by fanc-WU** [higlass/higlass-python#46] opened 2019-12-22 00:23 UTC
Hello~

May I ask for some help regarding a minor issue? higlass-python has been working well (and better and better) for me. However, after I started using higlass-python, each time I create a jupyter notebook in whichever directory, a file named "higlass-python.log" will show up in the same directory. This file is, not surprisingly, empty. I have shut down all the kernels through `Kernel -> Shut Down All Kernels` in jupyter. But still, when I create a new notebook, higlass-python.log will show up. 

This is not a huge issue but just a bit annoying and confusing. May I get some assistance?

Thank you so much!

**Comment by pkerpedjiev** [comment] 2020-01-05 19:40
Sorry, for the delayed reply. This is indeed an annoying issue. The problem is this line:

https://github.com/higlass/higlass-python/blob/f34a9a58af5dc53456aa20b89c8ddd924fd04faf/higlass/client.py#L9

@nvictus do you know if that's necessary or can we get rid of it?

**Comment by fanc-WU** [comment] 2020-01-09 20:43
Please fix this if it's an easy thing to do. Imagine having a higlass log file in your every folder...

Cheers~

**Comment by pkerpedjiev** [comment] 2020-01-09 21:11
No need to imagine, I use higlass-python too ;-)

Anyway, here's a PR to fix it: https://github.com/higlass/higlass-python/pull/52

Once it gets reviewed, it will be included in the next release.

**Comment by fanc-WU** [comment] 2020-01-09 21:12
Thank you so much for pointing out!!

**Closed** 2020-01-16 23:35 UTC
