### ISSUE TITLE
No module named 'higlass.client'

### ISSUE THREAD

**Issue by jiangshan529** [higlass/higlass-python#126] opened 2023-05-31 20:12 UTC
Hi, I have installed higlass-python and run it in jupyter notebook using these codes:
```
import higlass
import higlass.client as hgc
import higlass.tilesets as hgti
ts1 = hgti.cooler('./hela_5k.cool')
tr1 = hgc.Track('heatmap',tileset=ts1)
View1 = hgc.View([tr1])
(display, server, viewconf) = higlass.display([view1])
display
```

And it shows: 
ModuleNotFoundError: No module named 'higlass.client'

**Comment by 1944498970** [comment] 2023-09-14 07:49
> Hi, I have installed higlass-python and run it in jupyter notebook using these codes:
> 
> ```
> import higlass
> import higlass.client as hgc
> import higlass.tilesets as hgti
> ts1 = hgti.cooler('./hela_5k.cool')
> tr1 = hgc.Track('heatmap',tileset=ts1)
> View1 = hgc.View([tr1])
> (display, server, viewconf) = higlass.display([view1])
> display
> ```
> 
> And it shows: ModuleNotFoundError: No module named 'higlass.client'

have you solved this problem?

**Comment by roniweiss12** [comment] 2023-09-26 10:22
I have the same issue...

**Comment by magspho** [comment] 2023-11-20 22:40
Same! I force-reintalled higlass-python following issue [#127](https://github.com/higlass/higlass-python/issues/127), and then had the issue in [#35]( https://github.com/higlass/higlass-python/issues/35), and then I'm having this problem...

**Comment by nvictus** [comment] 2023-11-20 22:52
@magspho That's because the syntax has changed in v1:

```python
import higlass as hg

ts1 = hg.cooler("./hela_5k.cool")
tr1 = ts1.track("heatmap")
view1 = hg.view(tr1)

view1
```

See the [documentation](https://docs-python.higlass.io/getting_started.html) for more.

**Comment by nvictus** [comment] 2023-11-20 22:52
Closing this because the v0.* API is deprecated and no longer supported.

**Closed by nvictus** 2023-11-20 22:52 UTC

**Comment by magspho** [comment] 2023-11-20 23:43
Thank you @nvictus !! But I still got `'LocalTileset' object has no attribute 'tileset_info'` and `'LocalTileset' object has no attribute 'track'` error. My .mcool file worked fine using cooler in terms of visualization.

**Comment by manzt** [comment] 2023-11-21 15:14
@magspho please provide a reproducible example, along with a code snippet and envirnonment information. I see that you re-installed higlass-python, but I'd recommend creating a new environment.

```sh
conda create --name higlass python=3.11
conda activate higlass
pip install jupyterlab higlass-python clodius
jupyterlab
```

```python
import higlass as hg

ts1 = hg.cooler("./hela_5k.mcool")  # must be a mcool
tr1 = ts1.track("heatmap")
view1 = hg.view(tr1)

view1
```

**Comment by shdemah** [comment] 2024-01-16 14:12
Collecting anywidget>=0.6.3 (from higlass-python)
  Could not find a version that satisfies the requirement anywidget>=0.6.3 (from higlass-python) (from versions: 0.0.5, 0.1.0)
No matching distribution found for anywidget>=0.6.3 (from higlass-python)
Note: you may need to restart the kernel to use updated packages.
